name: Publish to NPM

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-js-version: '18'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci || npm install
        
      - name: Run tests
        run: npm test
        
      - name: Verify integrity
        run: node claude-guard.js --verify-integrity
        
      - name: Update package repository URL
        run: |
          npm pkg set repository.url="git+https://github.com/dwillitzer/claude-guard-community.git"
          npm pkg set bugs.url="https://github.com/dwillitzer/claude-guard-community/issues"
          npm pkg set homepage="https://github.com/dwillitzer/claude-guard-community#readme"
          
      - name: Publish to NPM
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}